### ISSUE TITLE
Copied files from Open Zeppelin instead of importing via NPM

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-distribution#29]
Ownable.sol and SafeMath.sol have been copied instead of imported via NPM.
When Zeppelin Solutions audit the code they will complain about this. See one of their past audits:

> Medium severity

> Install OpenZeppelin via NPM and Update
> Contactable, Pausable, SafeMath, Ownable, ERC20Basic, ERC20, BasicToken, and StandardToken were copied from the OpenZeppelin repository.
> 
> This violates OpenZeppelin’s MIT license, which requires the license and copyright notice to be included if its code is used, and makes it difficult and error-prone to update to a more recent version.

**Comment by Everhusk** [comment]
Yeah you're right on this, don't understand why they do this.. npm has always been a bit of a security concern itself.
